### ISSUE TITLE
I assume it is this paper?

### ISSUE THREAD

**Issue by mkdoherty** [SchlossLab/Schloss_Cluster_PeerJ_2015#1]
He et al. 2015. Stability of operational taxonomic units: an important but neglected property for analyzing microbial diversity. Microbiome. 2015 May 20;3:20. doi: 10.1186/s40168-015-0081-x. eCollection 2015.
http://www.ncbi.nlm.nih.gov/pubmed/25995836

PMCpdf->http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4438525/

**Comment by pschloss** [comment]
Yep.
